"""initial migration

Revision ID: 41881940cb66
Revises: 
Create Date: 2025-03-31 19:50:51.388430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41881940cb66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', 'SOMMELIER', name='userrole'), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.Column('wine_knowledge', sa.JSON(), nullable=True),
    sa.Column('wine_preferences', sa.JSON(), nullable=True),
    sa.Column('budget_preferences', sa.JSON(), nullable=True),
    sa.Column('taste_profile', sa.JSON(), nullable=True),
    sa.Column('rating_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('user')
    # ### end Alembic commands ###
